/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MyRectangle: typeof import('./src/components/MyRectangle.vue')['default']
    WelcomeIcon: typeof import('./src/components/WelcomeIcon.vue')['default']
  }
}
